#ifdef SQLITE_ENABLE_FTS3
# undef SQLITE_ENABLE_FTS3
#endif

#ifdef SQLITE_ENABLE_FTS4
# undef SQLITE_ENABLE_FTS4
#endif

#ifdef SQLITE_ENABLE_FTS5
# undef SQLITE_ENABLE_FTS5
#endif

#ifdef SQLITE_ENABLE_RTREE
# undef SQLITE_ENABLE_RTREE
#endif

#ifdef SQLITE_ENABLE_DBPAGE_VTAB
# undef SQLITE_ENABLE_DBPAGE_VTAB
#endif

#ifdef SQLITE_ENABLE_DBSTAT_VTAB
# undef SQLITE_ENABLE_DBSTAT_VTAB
#endif

#ifdef SQLITE_ENABLE_DESERIALIZE
# undef SQLITE_ENABLE_DESERIALIZE
#endif

#ifdef SQLITE_ENABLE_RBU
# undef SQLITE_ENABLE_RBU
#endif

#ifdef SQLITE_ENABLE_SESSION
# undef SQLITE_ENABLE_SESSION
#endif

#ifdef SQLITE_ENABLE_GEOPOLY
# undef SQLITE_ENABLE_GEOPOLY
#endif

#ifdef SQLITE_ENABLE_ICU
# undef SQLITE_ENABLE_ICU
#endif

#ifdef SQLITE_ENABLE_IOTRACE
# undef SQLITE_ENABLE_IOTRACE
#endif

#ifdef SQLITE_ENABLE_MATH_FUNCTIONS
# undef SQLITE_ENABLE_MATH_FUNCTIONS
#endif
#define SQLITE_ENABLE_MATH_FUNCTIONS

#ifdef SQLITE_ENABLE_JSON1
# undef SQLITE_ENABLE_JSON1
#endif

// we cannot release memory on requirest (why should we?)
#ifdef SQLITE_ENABLE_MEMORY_MANAGEMENT
# undef SQLITE_ENABLE_MEMORY_MANAGEMENT
#endif

#ifdef SQLITE_ENABLE_NORMALIZE
# undef SQLITE_ENABLE_NORMALIZE
#endif
#define SQLITE_ENABLE_NORMALIZE

#ifdef SQLITE_ENABLE_OFFSET_SQL_FUNC
# undef SQLITE_ENABLE_OFFSET_SQL_FUNC
#endif

#ifdef SQLITE_ENABLE_PREUPDATE_HOOK
# undef SQLITE_ENABLE_PREUPDATE_HOOK
#endif

#ifdef SQLITE_ENABLE_SNAPSHOT
# undef SQLITE_ENABLE_SNAPSHOT
#endif

#ifdef SQLITE_ENABLE_STMT_SCANSTATUS
# undef SQLITE_ENABLE_STMT_SCANSTATUS
#endif

#ifdef SQLITE_ENABLE_STMTVTAB
# undef SQLITE_ENABLE_STMTVTAB
#endif

#ifdef SQLITE_ENABLE_SQLLOG
# undef SQLITE_ENABLE_SQLLOG
#endif

#ifdef SQLITE_SOUNDEX
# undef SQLITE_SOUNDEX
#endif
#define SQLITE_SOUNDEX

#ifdef SQLITE_USE_FCNTL_TRACE
# undef SQLITE_USE_FCNTL_TRACE
#endif

#ifdef SQLITE_HAVE_ZLIB
# undef SQLITE_HAVE_ZLIB
#endif

// don't do it
#ifdef SQLITE_DISABLE_DIRSYNC
# undef SQLITE_DISABLE_DIRSYNC
#endif



// the double-quoted string literal misfeature
// ENABLED
#ifdef SQLITE_DQS
# undef SQLITE_DQS
#endif
#define SQLITE_DQS 3

// multithreading support
// DISABLED!
#ifdef SQLITE_THREADSAFE
# undef SQLITE_THREADSAFE
#endif
#define SQLITE_THREADSAFE 0

// memory limits and such
// DISABLED
#ifdef SQLITE_DEFAULT_MEMSTATUS
# undef SQLITE_DEFAULT_MEMSTATUS
#endif
#define SQLITE_DEFAULT_MEMSTATUS 0

// how to sync db data
// DISABLED
#ifdef SQLITE_DEFAULT_WAL_SYNCHRONOUS
# undef SQLITE_DEFAULT_WAL_SYNCHRONOUS
#endif
#define SQLITE_DEFAULT_WAL_SYNCHRONOUS 0

// LIKE should be slower, but match blobs
#ifdef SQLITE_LIKE_DOESNT_MATCH_BLOBS
# undef SQLITE_LIKE_DOESNT_MATCH_BLOBS
#endif

#ifdef SQLITE_MAX_EXPR_DEPTH
# undef SQLITE_MAX_EXPR_DEPTH
#endif
#define SQLITE_MAX_EXPR_DEPTH 1000


#ifdef SQLITE_OMIT_ALTERTABLE
# undef SQLITE_OMIT_ALTERTABLE
#endif

#ifdef SQLITE_OMIT_ANALYZE
# undef SQLITE_OMIT_ANALYZE
#endif

#ifdef SQLITE_OMIT_ATTACH
# undef SQLITE_OMIT_ATTACH
#endif

#ifdef SQLITE_OMIT_AUTHORIZATION
# undef SQLITE_OMIT_AUTHORIZATION
#endif

#ifdef SQLITE_OMIT_AUTOINCREMENT
# undef SQLITE_OMIT_AUTOINCREMENT
#endif

#ifdef SQLITE_OMIT_AUTOINIT
# undef SQLITE_OMIT_AUTOINIT
#endif

#ifdef SQLITE_OMIT_AUTOMATIC_INDEX
# undef SQLITE_OMIT_AUTOMATIC_INDEX
#endif

#ifdef SQLITE_OMIT_AUTORESET
# undef SQLITE_OMIT_AUTORESET
#endif

#ifdef SQLITE_OMIT_AUTOVACUUM
# undef SQLITE_OMIT_AUTOVACUUM
#endif

#ifdef SQLITE_OMIT_BETWEEN_OPTIMIZATION
# undef SQLITE_OMIT_BETWEEN_OPTIMIZATION
#endif

#ifdef SQLITE_OMIT_BLOB_LITERAL
# undef SQLITE_OMIT_BLOB_LITERAL
#endif

#ifdef SQLITE_OMIT_CASE_SENSITIVE_LIKE_PRAGMA
# undef SQLITE_OMIT_CASE_SENSITIVE_LIKE_PRAGMA
#endif

#ifdef SQLITE_OMIT_CAST
# undef SQLITE_OMIT_CAST
#endif

#ifdef SQLITE_OMIT_CHECK
# undef SQLITE_OMIT_CHECK
#endif

#ifdef SQLITE_OMIT_COMPILEOPTION_DIAGS
# undef SQLITE_OMIT_COMPILEOPTION_DIAGS
#endif

// we don't need cli completion
#ifdef SQLITE_OMIT_COMPLETE
# undef SQLITE_OMIT_COMPLETE
#endif
#define SQLITE_OMIT_COMPLETE

#ifdef SQLITE_OMIT_COMPOUND_SELECT
# undef SQLITE_OMIT_COMPOUND_SELECT
#endif

#ifdef SQLITE_OMIT_CTE
# undef SQLITE_OMIT_CTE
#endif

#ifdef SQLITE_OMIT_DATETIME_FUNCS
# undef SQLITE_OMIT_DATETIME_FUNCS
#endif

#ifdef SQLITE_OMIT_DECLTYPE
# undef SQLITE_OMIT_DECLTYPE
#endif

#ifdef SQLITE_OMIT_DEPRECATED
# undef SQLITE_OMIT_DEPRECATED
#endif
#define SQLITE_OMIT_DEPRECATED

#ifdef SQLITE_OMIT_DESERIALIZE
# undef SQLITE_OMIT_DESERIALIZE
#endif
#define SQLITE_OMIT_DESERIALIZE

#ifdef SQLITE_OMIT_DISKIO
# undef SQLITE_OMIT_DISKIO
#endif

#ifdef SQLITE_OMIT_EXPLAIN
# undef SQLITE_OMIT_EXPLAIN
#endif
#define SQLITE_OMIT_EXPLAIN

#ifdef SQLITE_OMIT_FLAG_PRAGMAS
# undef SQLITE_OMIT_FLAG_PRAGMAS
#endif

#ifdef SQLITE_OMIT_FLOATING_POINT
# undef SQLITE_OMIT_FLOATING_POINT
#endif

#ifdef SQLITE_OMIT_FOREIGN_KEY
# undef SQLITE_OMIT_FOREIGN_KEY
#endif

#ifdef SQLITE_OMIT_GENERATED_COLUMNS
# undef SQLITE_OMIT_GENERATED_COLUMNS
#endif

#ifdef SQLITE_OMIT_GET_TABLE
# undef SQLITE_OMIT_GET_TABLE
#endif

#ifdef SQLITE_OMIT_HEX_INTEGER
# undef SQLITE_OMIT_HEX_INTEGER
#endif

#ifdef SQLITE_OMIT_INCRBLOB
# undef SQLITE_OMIT_INCRBLOB
#endif

// no need
#ifdef SQLITE_OMIT_INTEGRITY_CHECK
# undef SQLITE_OMIT_INTEGRITY_CHECK
#endif
#define SQLITE_OMIT_INTEGRITY_CHECK

#ifdef SQLITE_OMIT_JSON
# undef SQLITE_OMIT_JSON
#endif
#define SQLITE_OMIT_JSON

#ifdef SQLITE_OMIT_LIKE_OPTIMIZATION
# undef SQLITE_OMIT_LIKE_OPTIMIZATION
#endif

#ifdef SQLITE_OMIT_LOAD_EXTENSION
# undef SQLITE_OMIT_LOAD_EXTENSION
#endif
#define SQLITE_OMIT_LOAD_EXTENSION

#ifdef SQLITE_OMIT_LOCALTIME
# undef SQLITE_OMIT_LOCALTIME
#endif

#ifdef SQLITE_OMIT_LOOKASIDE
# undef SQLITE_OMIT_LOOKASIDE
#endif

#ifdef SQLITE_OMIT_MEMORYDB
# undef SQLITE_OMIT_MEMORYDB
#endif

#ifdef SQLITE_OMIT_OR_OPTIMIZATION
# undef SQLITE_OMIT_OR_OPTIMIZATION
#endif

#ifdef SQLITE_OMIT_PAGER_PRAGMAS
# undef SQLITE_OMIT_PAGER_PRAGMAS
#endif

#ifdef SQLITE_OMIT_PRAGMA
# undef SQLITE_OMIT_PRAGMA
#endif

#ifdef SQLITE_OMIT_PROGRESS_CALLBACK
# undef SQLITE_OMIT_PROGRESS_CALLBACK
#endif

#ifdef SQLITE_OMIT_QUICKBALANCE
# undef SQLITE_OMIT_QUICKBALANCE
#endif

#ifdef SQLITE_OMIT_REINDEX
# undef SQLITE_OMIT_REINDEX
#endif

#ifdef SQLITE_OMIT_SCHEMA_PRAGMAS
# undef SQLITE_OMIT_SCHEMA_PRAGMAS
#endif

#ifdef SQLITE_OMIT_SCHEMA_VERSION_PRAGMAS
# undef SQLITE_OMIT_SCHEMA_VERSION_PRAGMAS
#endif

#ifdef SQLITE_OMIT_SHARED_CACHE
# undef SQLITE_OMIT_SHARED_CACHE
#endif

#ifdef SQLITE_OMIT_SUBQUERY
# undef SQLITE_OMIT_SUBQUERY
#endif

#ifdef SQLITE_OMIT_TCL_VARIABLE
# undef SQLITE_OMIT_TCL_VARIABLE
#endif

#ifdef SQLITE_OMIT_TEMPDB
# undef SQLITE_OMIT_TEMPDB
#endif

#ifdef SQLITE_OMIT_TRACE
# undef SQLITE_OMIT_TRACE
#endif
#define SQLITE_OMIT_TRACE

#ifdef SQLITE_OMIT_TRIGGER
# undef SQLITE_OMIT_TRIGGER
#endif

#ifdef SQLITE_OMIT_TRUNCATE_OPTIMIZATION
# undef SQLITE_OMIT_TRUNCATE_OPTIMIZATION
#endif

#ifdef SQLITE_OMIT_UTF16
# undef SQLITE_OMIT_UTF16
#endif

// please, don't
#ifdef SQLITE_OMIT_VACUUM
# undef SQLITE_OMIT_VACUUM
#endif
#define SQLITE_OMIT_VACUUM

#ifdef SQLITE_OMIT_VIEW
# undef SQLITE_OMIT_VIEW
#endif

#ifdef SQLITE_OMIT_VIRTUALTABLE
# undef SQLITE_OMIT_VIRTUALTABLE
#endif

#ifdef SQLITE_OMIT_WAL
# undef SQLITE_OMIT_WAL
#endif

#ifdef SQLITE_OMIT_WINDOWFUNC
# undef SQLITE_OMIT_WINDOWFUNC
#endif

#ifdef SQLITE_OMIT_WSD
# undef SQLITE_OMIT_WSD
#endif

#ifdef SQLITE_OMIT_XFER_OPT
# undef SQLITE_OMIT_XFER_OPT
#endif

#ifdef SQLITE_UNTESTABLE
# undef SQLITE_UNTESTABLE
#endif
#define SQLITE_UNTESTABLE

#ifdef SQLITE_ZERO_MALLOC
# undef SQLITE_ZERO_MALLOC
#endif


#ifdef SQLITE_DEBUG
# undef SQLITE_DEBUG
#endif

#ifdef SQLITE_MEMDEBUG
# undef SQLITE_MEMDEBUG
#endif


#ifdef SQLITE_WIN32_HEAP_CREATE
# undef SQLITE_WIN32_HEAP_CREATE
#endif

#ifdef SQLITE_WIN32_MALLOC_VALIDATE
# undef SQLITE_WIN32_MALLOC_VALIDATE
#endif


#ifdef SQLITE_USE_ALLOCA
# undef SQLITE_USE_ALLOCA
#endif

/*
#ifdef SQLITE_DEFAULT_FILE_FORMAT
# undef SQLITE_DEFAULT_FILE_FORMAT
#endif
#define SQLITE_DEFAULT_FILE_FORMAT 4
*/

#ifdef SQLITE_DEFAULT_FOREIGN_KEYS
# undef SQLITE_DEFAULT_FOREIGN_KEYS
#endif
#define SQLITE_DEFAULT_FOREIGN_KEYS 0

// turn of mmap logic
#ifdef SQLITE_DEFAULT_MMAP_SIZE
# undef SQLITE_DEFAULT_MMAP_SIZE
#endif
#define SQLITE_DEFAULT_MMAP_SIZE 0

#ifdef SQLITE_MAX_MMAP_SIZE
# undef SQLITE_MAX_MMAP_SIZE
#endif
#define SQLITE_MAX_MMAP_SIZE 0

#ifdef SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT
# undef SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT
#endif

#ifdef SQLITE_DEFAULT_LOCKING_MODE
# undef SQLITE_DEFAULT_LOCKING_MODE
#endif
#define SQLITE_DEFAULT_LOCKING_MODE 0

#ifdef SQLITE_DEFAULT_WAL_AUTOCHECKPOINT
# undef SQLITE_DEFAULT_WAL_AUTOCHECKPOINT
#endif

#ifdef SQLITE_DEFAULT_WORKER_THREADS
# undef SQLITE_DEFAULT_WORKER_THREADS
#endif

#ifdef SQLITE_MAX_WORKER_THREADS
# undef SQLITE_MAX_WORKER_THREADS
#endif
#define SQLITE_MAX_WORKER_THREADS 0

#ifdef SQLITE_EXTRA_DURABLE
# undef SQLITE_EXTRA_DURABLE
#endif

#ifdef SQLITE_FTS3_MAX_EXPR_DEPTH
# undef SQLITE_FTS3_MAX_EXPR_DEPTH
#endif
#define SQLITE_FTS3_MAX_EXPR_DEPTH 12

#ifdef SQLITE_MAX_SCHEMA_RETRY
# undef SQLITE_MAX_SCHEMA_RETRY
#endif
#define SQLITE_MAX_SCHEMA_RETRY 42

// why not?
#ifdef SQLITE_POWERSAFE_OVERWRITE
# undef SQLITE_POWERSAFE_OVERWRITE
#endif
#define SQLITE_POWERSAFE_OVERWRITE 1

// let's play safe
#ifdef SQLITE_4_BYTE_ALIGNED_MALLOC
# undef SQLITE_4_BYTE_ALIGNED_MALLOC
#endif
#define SQLITE_4_BYTE_ALIGNED_MALLOC

#ifdef SQLITE_TRUSTED_SCHEMA
# undef SQLITE_TRUSTED_SCHEMA
#endif
#define SQLITE_TRUSTED_SCHEMA 1

#ifdef SQLITE_USE_URI
# undef SQLITE_USE_URI
#endif
#define SQLITE_USE_URI

#ifdef SQLITE_ALLOW_URI_AUTHORITY
# undef SQLITE_ALLOW_URI_AUTHORITY
#endif

#ifdef SQLITE_ENABLE_API_ARMOR
# undef SQLITE_ENABLE_API_ARMOR
#endif

#ifdef SQLITE_ENABLE_ATOMIC_WRITE
# undef SQLITE_ENABLE_ATOMIC_WRITE
#endif

#ifdef SQLITE_ENABLE_BATCH_ATOMIC_WRITE
# undef SQLITE_ENABLE_BATCH_ATOMIC_WRITE
#endif

#ifdef SQLITE_ENABLE_BYTECODE_VTAB
# undef SQLITE_ENABLE_BYTECODE_VTAB
#endif

#ifdef SQLITE_ENABLE_COLUMN_METADATA
# undef SQLITE_ENABLE_COLUMN_METADATA
#endif
#define SQLITE_ENABLE_COLUMN_METADATA

#ifdef SQLITE_ENABLE_EXPLAIN_COMMENTS
# undef SQLITE_ENABLE_EXPLAIN_COMMENTS
#endif
