#!/bin/sh

odir=`pwd`
mdir=`dirname "$0"`
cd "$mdir"


DECAL_SRC="tpl.decaldef.txt"
DECAL_DEST="../../k8_decaldef_gore.txt"

DECORATE_SRC="tpl.decorate.txt"
DECORATE_DEST="../../actors/k8gore/k8goreactors.txt"


DECAL_SHADE_RED="50"
#DECAL_SHADE_GREEN="50"
#DECAL_SHADE_BLUE="50"
# still using old decals
DECAL_SHADE_RED_TRANSIENT="4f"
#DECAL_SHADE_GREEN_TRANSIENT="4f"
#DECAL_SHADE_BLUE_TRANSIENT="6f"


rm $DECORATE_DEST $DECAL_DEST 2>/dev/null

echo '/////////////////////////////////////////////////////////' >>$DECORATE_DEST
echo '// WARNING! THIS IS AUTOGENERATED FILE! DO NOT CHANGE! //' >>$DECORATE_DEST
echo '/////////////////////////////////////////////////////////' >>$DECORATE_DEST

echo '/////////////////////////////////////////////////////////' >>$DECAL_DEST
echo '// WARNING! THIS IS AUTOGENERATED FILE! DO NOT CHANGE! //' >>$DECAL_DEST
echo '/////////////////////////////////////////////////////////' >>$DECAL_DEST

# WARNING! level death notifier will not be called for overlimit entity!
echo 'Actor K8Gore_BloodBase { LimitWithSubCvar "k8GoreOpt_MaxBloodEntities" +NoTeleport }' >>$DECORATE_DEST
echo 'Actor K8Gore_BloodBaseTransient : K8Gore_BloodBase { LimitWithSubCvar "k8GoreOpt_MaxTransientBloodEntities" +NoTeleport }' >>$DECORATE_DEST
echo "k8vavoom { AllowBloodReplacement = true }" >>$DECORATE_DEST
# this is required to create blood translations for colored blood option
# no need too, because we can create blood translations on the fly now
#echo "Actor K8Gore_BloodTranslationGreen { BloodColor \"00 40 00\" }" >>$DECORATE_DEST
#echo "Actor K8Gore_BloodTranslationBlue { BloodColor \"00 00 40\" }" >>$DECORATE_DEST


echo "////////////////////////////////////////////////////////////////////////////////" >>$DECORATE_DEST
echo "// BASE RED BLOOD" >>$DECORATE_DEST
echo "////////////////////////////////////////////////////////////////////////////////" >>$DECORATE_DEST

echo "////////////////////////////////////////////////////////////////////////////////" >>$DECAL_DEST
echo "// BASE RED BLOOD" >>$DECAL_DEST
echo "////////////////////////////////////////////////////////////////////////////////" >>$DECAL_DEST

rdmd zprepro.d Shade=$DECAL_SHADE_RED --append Type= $DECORATE_SRC $DECORATE_DEST
rdmd zprepro.d Shade=$DECAL_SHADE_RED --append Type= $DECAL_SRC $DECAL_DEST


echo "" >>$DECORATE_DEST
echo "" >>$DECORATE_DEST
echo "" >>$DECORATE_DEST
echo "////////////////////////////////////////////////////////////////////////////////" >>$DECORATE_DEST
echo "// BASE RED TRANSIENT BLOOD" >>$DECORATE_DEST
echo "////////////////////////////////////////////////////////////////////////////////" >>$DECORATE_DEST

echo "" >>$DECAL_DEST
echo "" >>$DECAL_DEST
echo "" >>$DECAL_DEST
echo "////////////////////////////////////////////////////////////////////////////////" >>$DECAL_DEST
echo "// BASE RED TRANSIENT BLOOD" >>$DECAL_DEST
echo "////////////////////////////////////////////////////////////////////////////////" >>$DECAL_DEST

rdmd zprepro.d Shade=$DECAL_SHADE_RED_TRANSIENT -DTRANSIENT --append Type=Transient $DECORATE_SRC $DECORATE_DEST
rdmd zprepro.d Shade=$DECAL_SHADE_RED_TRANSIENT -DTRANSIENT --append Type=Transient $DECAL_SRC $DECAL_DEST

#cat decals_bootprints.txt >>$DECAL_DEST

# colored blood is done by the engine with built-in blood translations now
